### ISSUE TITLE
Breeding graph showing negative numbers when no breeding data

### ISSUE THREAD

**Issue by dbl3raf** [bird-team/brisbane-bird-atlas#114]
The breeding graph, e.g. for brolga, shows negative numbers on the y axis when no breeding data are available. Sometimes we will want to show a blank breeding graph, in cases where the species might have bred in Brisbane, but we don't yet have any evidence, e.g. rock dove. Can we force the y axis minimum to be 0?
![image](https://user-images.githubusercontent.com/23551540/49757954-5fe24f00-fd09-11e8-8fc1-a967b77241c8.png)

**Comment by jeffreyhanson** [comment]
I've just pushed some code that should manually set the ylimits from [0, 1] if the range of the data is [0, 0]

**Comment by jeffreyhanson** [comment]
Can you try rebuilding the assets and verify that it worked?

**Comment by Louis-Backstrom** [comment]
This doesn't seem to be fixed on the latest set of assets - even though they're being cantankerous the actual graphs themselves seem to have pushed fine.

**Comment by jeffreyhanson** [comment]
Ok - I've just pushed a patch which should fix this - can someone please try remaking the assets and see if this fixes it? We should be able to see if this fixes it by looking at the [brown capped emerald dove](https://brisbanebirds.com/brown-capped-emerald-dove-chalcophaps-longirostris.html#brown-capped-emerald-dove-chalcophaps-longirostris).

**Comment by Louis-Backstrom** [comment]
See [other thread](https://github.com/bird-team/brisbane-bird-atlas/issues/119#issuecomment-468978435)

**Comment by Louis-Backstrom** [comment]
This still doesn't appear to have fixed the issue, but I have a suspicion the code won't have overridden the existing graphs as there's no difference in the data - I have been using `make pull_assets` to save time. I am going to try a complete rebuild from scratch of the assets once I've successfully got the surveyor sheets in storage (working on that right now) and will see if that fixes it.

**Comment by jeffreyhanson** [comment]
Yeah, that's probably the case. Great idea - thanks!

**Comment by Louis-Backstrom** [comment]
I'm hoping so - surveyor sheets are nearly done uploading manually (hopefully) so I'll get onto it soon.

**Comment by Louis-Backstrom** [comment]
Starting a remake now.

**Comment by Louis-Backstrom** [comment]
This has been successfully fixed with the latest rebuild of the assets:

![image](https://user-images.githubusercontent.com/44354406/53765878-fd21dd80-3f1c-11e9-937e-45908fb25474.png)

Doesn't seem to be showing up on the website yet, but I'm hoping it will once it's rebuilt (the file `assets-graphs.zip` under "Atlas asset and document storage" has the updated files, so it pushed successfully too). Closing this issue for now unless something goes wrong.

**Comment by jeffreyhanson** [comment]
Brilliant - thanks!
