### ISSUE TITLE
Magpie goose image displaying too small in the PDF

### ISSUE THREAD

**Issue by dbl3raf** [bird-team/brisbane-bird-atlas#98]
the magpie goose image is displaying too small in the PDF version, contra e.g. the plumed whistling duck in the very next account. Any ideas why this might be / how to fix it?

**Comment by jeffreyhanson** [comment]
Yeah that's strange, I'll see what I can do.

**Comment by jeffreyhanson** [comment]
I can't seem to get it working. Can you please crop the image to the correct dimensions, upload it to flickr, and update the spreadsheet with the new url, and see if that fixes it?

**Comment by dbl3raf** [comment]
apparently fixed now, and being discussed more broadly in another issue

**Comment by jeffreyhanson** [comment]
OK - that's good to hear - still don't know why it wasn't working though (hopefully if we standardize all the image aspect ratios this shouldn't crop up again)
